# Generated by Django 4.1.5 on 2023-01-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_vacancies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relevance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Получить информацию')),
                ('content', models.FileField(upload_to='admin')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Востребованность',
            },
        ),
    ]
