# Generated by Django 4.1.5 on 2023-01-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_relevance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relevance',
            name='content',
            field=models.FileField(upload_to='app/admin'),
        ),
    ]
